name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - run: docker build -t joaoglp/react-test-vite -f Dockerfile.dev .
      - run: docker run -e CI=true joaoglp/react-test-vite npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend-vite
          environment_name: Frontend-vite-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-782634014534
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
